# Generated by Django 4.0.5 on 2022-06-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제 일자')),
                ('is_acitve', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('name', models.CharField(max_length=10, verbose_name='카테고리명')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
