# Generated by Django 4.0.5 on 2022-07-13 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='수량')),
                ('buy', models.BooleanField(default=False, verbose_name='구매 여부')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제 일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('name', models.CharField(max_length=10, verbose_name='카테고리명')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='구매 일자')),
                ('transaction_id', models.DateTimeField(verbose_name='주문번호')),
                ('status', models.CharField(choices=[('PAY_COMPLETE', '결제 완료'), ('PREPARING', '배송 준비중'), ('SHIPPING', '배송중'), ('DELIVER', '배송 완료')], default='PAY_COMPLETE', max_length=15)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='수량')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제 일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('title', models.CharField(max_length=30, verbose_name='제품명')),
                ('thumnail', models.ImageField(null=True, upload_to='product/thumbnail', verbose_name='썸네일')),
                ('description', models.TextField(verbose_name='설명')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='카테고리')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제 일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('name', models.CharField(max_length=15, verbose_name='옵션명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option', to='product.product', verbose_name='상품명')),
            ],
            options={
                'db_table': 'product_option',
            },
        ),
    ]
