# Generated by Django 4.0.5 on 2022-06-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
