# Generated by Django 4.0.5 on 2022-06-24 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_rename_is_acitve_category_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제 일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('title', models.CharField(max_length=30, verbose_name='제품명')),
                ('thumnail', models.ImageField(upload_to='product/thumbnail', verbose_name='썸네일')),
                ('description', models.TextField(verbose_name='설명')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='카테고리')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제 일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('name', models.CharField(max_length=15, verbose_name='옵션명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품명')),
            ],
            options={
                'db_table': 'product_option',
            },
        ),
    ]
