# Generated by Django 4.0.5 on 2022-06-28 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_product_productoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='구매 시각')),
                ('transaction_id', models.CharField(max_length=100, null=True, verbose_name='거래 번호')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('address', models.CharField(max_length=100, verbose_name='배송지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-order_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='수량')),
                ('created_at', models.DateTimeField(verbose_name='생성 날짜')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order', verbose_name='구매 정보')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productoption', verbose_name='상품')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='수량')),
                ('ordered', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option', to='product.productoption', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
