# Generated by Django 4.0.5 on 2022-07-01 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order_product_like_orderitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option', to='product.product', verbose_name='상품명'),
        ),
    ]
